on: [push]

jobs:
  my-job:
    name: 'Job'
    runs-on: ubuntu-latest

    steps:
    - name: 'Step: Code Checkout'
      uses: actions/checkout@v2
      
    - name: 'Step: Run the action'
      id: hello
      uses: ./
      with:
        myInput: 'Paul McCarron'
    - name: 'Step: Output the memory'
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "my secrets is =" ${{ secrets.AZURE_PUBLISH_PROFILE }}
        echo "total memory successfully output"
